### ISSUE TITLE
Passwords are being stored in plain text

### ISSUE THREAD

**Issue by elliott-space-track** [Exclosure/space-track-cache#1]
In `server/handler.py`, line 66 prints usernames and passwords to standard out in plain text. AWS Lambda will write these statements to logs, making them available via Lambda or CloudWatch. Please restructure your code to not retain usernames and passwords.

**Comment by meawoppl** [comment]
Thanks for reporting this here and in our earlier conversation on Twitter. This is certainly an issue, and we will have a patch out for it shortly.

**Comment by meawoppl** [comment]
@elliott-space-track I put out a RFC that I tagged you on. Does this change set address your concerns?

**Comment by elliott-space-track** [comment]
Looks fine to me. We would also request that you purge your existing logs to remove any usernames / passwords that have already been stored, as previously discussed.

**Comment by meawoppl** [comment]
There are a couple active users (astronomers from the SATCON2 workshop), so I am waiting until tomorrow for our regularly scheduled deployment window.

We will purge all logs from this lambda following that deploy, and close this issue after confirmation.

**Comment by meawoppl** [comment]
Merged #2

**Comment by meawoppl** [comment]
Done!
